#!/usr/bin/env node

var forever = require('forever');
var music = '/music';

forever.start('/music/music', {
  max: 3,
  silent: false,
  cwd: music,
  outFile: music + '/out.log',
  errFile: music + '/err.log'
});
